---
baseURL: "/"
languageCode: en-us
title: Zooey
module:
  imports:
  - path: github.com/themefisher/parsa-hugo
    mounts:
    - source: layouts
      target: layouts
    - source: assets
      target: assets
    - source: static
      target: static
    - source: exampleSite/static/images
      target: static/images
summaryLength: '10'
paginate: '6'
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  plugins:
    css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/slick/slick.css
    - link: plugins/themify-icons/themify-icons.css
    js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/headroom/headroom.js
    - link: plugins/instafeed/instafeed.min.js
    - link: plugins/masonry/masonry.js
    - link: plugins/reading-time/readingTime.min.js
    - link: plugins/smooth-scroll/smooth-scroll.js
    - link: plugins/search/fuse.min.js
    - link: plugins/search/mark.js
    - link: plugins/search/search.js
  logo: ''
  home: Home
  layout: '1'
  description: ''
  preloader: true
  search: true
  author: ''
  author_image: ''
  bio: The world's first zoosexual lifestyle magazine!
  mobile: ''
  email: Zooeymagazine@protonmail.me
  address: ''
  contact_form_action: ''
  google_analitycs_id: ''
  copyright: "(c) Zooey Publishing 2022"
  instafeed:
    enable: false
    access_token: IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
  social:
  - icon: ti-twitter-alt
    URL: "#www.twitter.com/ZooeyDotPub"
menu:
  main:
  - url: twitter.com
    name: twitter
    weight: 4
  - URL: about
    name: About
    weight: 1
  - URL: contact
    name: Submit an Article
    weight: 2
